---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
- type: directory
  path: content
  label: Content
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=#{self.site_settings.engine_version || '0.17'}
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=#{self.site_settings.engine_version || '0.17'}
  output_directory: public
